import { Icon } from "@iconify/react";

export const producerArray = [
  {
    id: 0,
    name: "labourer",
    output: 1,
    cost: 5,
    owned: 0,
    icon: <Icon icon="mdi:sickle" />,
    buyType: "purchase",
  },
  {
    id: 1,
    name: "bazaar",
    output: 5,
    cost: 50,
    owned: 0,
    icon: <Icon icon="healthicons:market-stall" />,
    buyType: "purchase",
  },
  {
    id: 2,
    name: "scribe",
    output: 120,
    cost: 600,
    owned: 0,
    icon: <Icon icon="game-icons:quill" />,
    buyType: "purchase",
  },
  {
    id: 3,
    name: "obelisk",
    output: 1000,
    cost: 5000,
    owned: 0,
    icon: <Icon icon="game-icons:obelisk" />,
    buyType: "construct",
  },
  {
    id: 4,
    name: "sphinx",
    output: 5000,
    cost: 25000,
    owned: 0,
    icon: <Icon icon="game-icons:egyptian-sphinx" />,
    buyType: "construct",
  },
  {
    id: 5,
    name: "pyramid",
    output: 10000,
    cost: 50000,
    owned: 0,
    icon: <Icon icon="game-icons:great-pyramid" />,
    buyType: "construct",
  },
  {
    id: 6,
    name: "cat deity",
    output: 100000,
    cost: 500000,
    owned: 0,
    icon: <Icon icon="fluent-mdl2:cat" />,
    buyType: "summon",
  },
  {
    id: 7,
    name: "alien assistance",
    output: 1000000,
    cost: 5000000,
    owned: 0,
    icon: <Icon icon="ph:alien-fill" />,
    buyType: "call for",
  },
];
